# Generated by Django 2.1.2 on 2020-03-12 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('AgencyId', models.AutoField(primary_key=True, serialize=False)),
                ('AgencyName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('LicenseNo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReg',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CusttomerName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('DistrictId', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HandicrafterReg',
            fields=[
                ('HandicrafterId', models.AutoField(primary_key=True, serialize=False)),
                ('HandicrafterName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationId', models.AutoField(primary_key=True, serialize=False)),
                ('LocationName', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('LoginId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='productphoto')),
                ('price', models.IntegerField()),
                ('status', models.IntegerField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Agency')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Category')),
                ('handicarft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.HandicrafterReg')),
            ],
        ),
        migrations.AddField(
            model_name='handicrafterreg',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Login'),
        ),
        migrations.AddField(
            model_name='customerreg',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Location'),
        ),
        migrations.AddField(
            model_name='customerreg',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Login'),
        ),
        migrations.AddField(
            model_name='agency',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Location'),
        ),
        migrations.AddField(
            model_name='agency',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handi.Login'),
        ),
    ]
