# Generated by Django 2.1.2 on 2020-03-13 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='handi.District'),
            preserve_default=False,
        ),
    ]
