# Generated by Django 2.1.2 on 2020-03-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handi', '0004_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='cardno',
            field=models.BigIntegerField(),
        ),
    ]
